const folaData = {
  // --- LÍNEA DE TIEMPO (Sin cambios) ---
  timeline: {
      2014: { series: [{ name: "Pokémon Y", result: "VICTORIA", character: "Folana", mvp: "Equipo", cover: "y.jpg" }, { name: "HeartGold", result: "VICTORIA", character: "Folana", mvp: "Furia", cover: "hg.jpg" }, { name: "Rubí", result: "DERROTA", character: "Fola", mvp: "Ninguno", cover: "rubi.jpg" }, { name: "Platino", result: "VICTORIA", character: "Folana", mvp: "Equipo", cover: "platino.jpg" }], hallOfFame: [{ name: "Furia", species: "Typhlosion", file: "typhlosion.gif" }, { name: "Roberto", species: "Ampharos", file: "ampharos.gif" }, { name: "Leviathan", species: "Gyarados", file: "gyarados.gif" }] },
      2015: { series: [{ name: "Light Platinum", result: "VICTORIA", character: "Fola", mvp: "Equipo", cover: "light_platinum.jpg" }, { name: "Rubí Omega", result: "DERROTA", character: "Folana", mvp: "Sisel", cover: "omega.jpg" }, { name: "Plata Hardlocke", result: "DERROTA", character: "Fola", mvp: "Ninguno", cover: "soulsilver.jpg" }, { name: "X Random", result: "VICTORIA", character: "Folana", mvp: "Equipo", cover: "x.jpg" }, { name: "Glazed", result: "VICTORIA", character: "Fola", mvp: "Equipo", cover: "glazed.jpg" }, { name: "Platino Random", result: "VICTORIA", character: "Fola", mvp: "Gunter", cover: "platino.jpg" }], hallOfFame: [{ name: "Sisel", species: "Gliscor", file: "gliscor.gif" }, { name: "Gunter", species: "Gengar", file: "gengar.gif" }, { name: "Lavita", species: "Kingdra", file: "kingdra.gif" }] },
      2016: { series: [{ name: "SoulSilver Dual", result: "DERROTA", character: "Fola", mvp: "Ragnar", cover: "soulsilver.jpg" }, { name: "Platino Starters", result: "VICTORIA", character: "Fola", mvp: "Greninja", cover: "platino.jpg" }, { name: "Oro Donalocke", result: "DERROTA", character: "Folana", mvp: "Ninguno", cover: "hg.jpg" }, { name: "Islas Doradas", result: "VICTORIA", character: "Fola", mvp: "Equipo", cover: "firered.jpg" }, { name: "Rojo Hardlocke", result: "VICTORIA", character: "Folana", mvp: "Equipo", cover: "firered.jpg" }, { name: "Negro 2 Dual", result: "VICTORIA", character: "Fola", mvp: "Equipo", cover: "black2.jpg" }], hallOfFame: [{ name: "Ragnar", species: "Nidoking", file: "nidoking.gif" }, { name: "Greninja", species: "Greninja", file: "greninja.gif" }, { name: "Luis", species: "Lucario", file: "lucario.gif" }] },
      2017: { series: [{ name: "Sol Random", result: "VICTORIA", character: "Fola", mvp: "Manolo", cover: "sol.jpg" }, { name: "Luna", result: "VICTORIA", character: "Folana", mvp: "Knekro", cover: "luna.jpg" }, { name: "Uranium", result: "DERROTA", character: "Fola", mvp: "Ninguno", cover: "uranium.jpg" }, { name: "Y Dual", result: "DERROTA", character: "Fola", mvp: "Ninguno", cover: "y.jpg" }, { name: "PLA Vidalocke", result: "DERROTA", character: "Folana", mvp: "Ninguno", cover: "arceus.jpg" }, { name: "Ultra Sol", result: "VICTORIA", character: "Fola", mvp: "Manolo", cover: "ultrasol.jpg" }], hallOfFame: [{ name: "Manolo", species: "Garchomp", file: "garchomp.gif" }, { name: "Knekro", species: "Mimikyu", file: "mimikyu.gif" }, { name: "Araquanid", species: "Araquanid", file: "araquanid.gif" }] },
      2018: { series: [{ name: "UltraSol Dual", result: "VICTORIA", character: "Fola", mvp: "Hax", cover: "ultrasol.jpg" }, { name: "UltraLuna Vida", result: "VICTORIA", character: "Folana", mvp: "Necrozma", cover: "ultraluna.jpg" }, { name: "Titan HardLocke", result: "DERROTA", character: "Fola", mvp: "Ninguno", cover: "sol.jpg" }, { name: "R2 ShinyLocke", result: "VICTORIA", character: "Folana", mvp: "Equipo", cover: "black2.jpg" }, { name: "Plata Dual", result: "DERROTA", character: "Fola", mvp: "Ninguno", cover: "soulsilver.jpg" }, { name: "Hoenn Adventures", result: "VICTORIA", character: "Fola", mvp: "Equipo", cover: "omega.jpg" }], hallOfFame: [{ name: "Hax", species: "Haxorus", file: "haxorus.gif" }, { name: "Pee", species: "Swampert", file: "swampert.gif" }, { name: "Metagross", species: "Metagross", file: "metagross.gif" }] },
      2019: { series: [{ name: "Pokémon Iberia", result: "VICTORIA", character: "Folana", mvp: "Turia", cover: "iberia.jpg" }, { name: "Diamante Dual", result: "VICTORIA", character: "Fola", mvp: "Garchomp", cover: "diamante.jpg" }, { name: "UltraSol Random", result: "DERROTA", character: "Folana", mvp: "Ninguno", cover: "ultrasol.jpg" }, { name: "RO Dual", result: "DERROTA", character: "Fola", mvp: "Ninguno", cover: "omega.jpg" }, { name: "X Vidalocke", result: "DERROTA", character: "Folana", mvp: "Ninguno", cover: "x.jpg" }, { name: "Oro Evolocke", result: "DERROTA", character: "Folana", mvp: "Ninguno", cover: "hg.jpg" }], hallOfFame: [{ name: "Turia", species: "Gyarados", file: "gyarados.gif" }, { name: "Don Quijote", species: "Gallade", file: "gallade.gif" }, { name: "Garchomp", species: "Garchomp", file: "garchomp.gif" }] },
      2020: { series: [{ name: "Oro Calvolocke", result: "VICTORIA", character: "Fola", mvp: "Dolan", cover: "hg.jpg" }, { name: "Espada Dual", result: "DERROTA", character: "Fola", mvp: "Cinderace", cover: "espada.jpg" }, { name: "Escudo Nuzlocke", result: "DERROTA", character: "Folana", mvp: "Ninguno", cover: "escudo.jpg" }, { name: "Sol Shiny", result: "DERROTA", character: "Fola", mvp: "Ninguno", cover: "sol.jpg" }, { name: "Opalo", result: "DERROTA", character: "Fola", mvp: "Ninguno", cover: "opalo.jpg" }, { name: "Blanco 2 Dual", result: "DERROTA", character: "Folana", mvp: "Ninguno", cover: "black2.jpg" }], hallOfFame: [{ name: "Dolan", species: "Snorlax", file: "snorlax.gif" }, { name: "Cinderace", species: "Cinderace", file: "cinderace.gif" }, { name: "Toxtricity", species: "Toxtricity", file: "toxtricity.gif" }] },
      2021: { series: [{ name: "Platino Mega", result: "VICTORIA", character: "Fola", mvp: "Luis", cover: "platino.jpg" }, { name: "Diamante B. Dual", result: "DERROTA", character: "Fola", mvp: "Staraptor", cover: "bdsp.jpg" }, { name: "Rojo Mega", result: "DERROTA", character: "Fola", mvp: "Ninguno", cover: "firered.jpg" }, { name: "Oro Mega", result: "VICTORIA", character: "Fola", mvp: "Equipo", cover: "hg.jpg" }, { name: "RO Mega", result: "DERROTA", character: "Fola", mvp: "Ninguno", cover: "omega.jpg" }, { name: "X Mega", result: "VICTORIA", character: "Fola", mvp: "Equipo", cover: "x.jpg" }], hallOfFame: [{ name: "Luis", species: "Lucario", file: "lucario.gif" }, { name: "Charizard", species: "Charizard", file: "charizard.gif" }, { name: "Gengar", species: "Gengar", file: "gengar.gif" }] },
      2022: { series: [{ name: "Leyendas Arceus", result: "VICTORIA", character: "Fola", mvp: "Ursaluna", cover: "arceus.jpg" }, { name: "Espada Soulink", result: "VICTORIA", character: "Folana", mvp: "Equipo", cover: "espada.jpg" }, { name: "Esmeralda Bebe", result: "VICTORIA", character: "Fola", mvp: "Equipo", cover: "esmeralda.jpg" }, { name: "Realidea", result: "VICTORIA", character: "Fola", mvp: "Equipo", cover: "realidea.jpg" }, { name: "Púrpura Wonder", result: "DERROTA", character: "Folana", mvp: "Ninguno", cover: "purpura.jpg" }], hallOfFame: [{ name: "Ursaluna", species: "Ursaluna", file: "ursaluna.gif" }, { name: "Kleavor", species: "Kleavor", file: "kleavor.gif" }, { name: "Goodra", species: "Goodra", file: "goodra.gif" }] },
      2023: { series: [{ name: "Glazed Hard", result: "DERROTA", character: "Folana", mvp: "Ninguno", cover: "glazed.jpg" }, { name: "Añil", result: "DERROTA", character: "Fola", mvp: "Ninguno", cover: "anil.jpg" }, { name: "Oro Sagrado", result: "DERROTA", character: "Folana", mvp: "Ninguno", cover: "hg.jpg" }, { name: "Infinite Fusion", result: "DERROTA", character: "Fola", mvp: "Ninguno", cover: "if.jpg" }, { name: "Voltaje Blanco", result: "DERROTA", character: "Fola", mvp: "Ninguno", cover: "black2.jpg" }], hallOfFame: [{ name: "Meowscarada", species: "Meowscarada", file: "meowscarada.gif" }, { name: "Skeledirge", species: "Skeledirge", file: "skeledirge.gif" }, { name: "Quaquaval", species: "Quaquaval", file: "quaquaval.gif" }] },
      2024: { series: [{ name: "Super Sol Dual", result: "VICTORIA", character: "Fola", mvp: "Paaola", cover: "sol.jpg" }, { name: "Super X Dual", result: "DERROTA", character: "Folana", mvp: "Ninguno", cover: "x.jpg" }, { name: "Super Rojo Dual", result: "VICTORIA", character: "Fola", mvp: "Cloyster", cover: "firered.jpg" }, { name: "Eternal X", result: "DERROTA", character: "Folana", mvp: "Ninguno", cover: "x.jpg" }, { name: "Super Zafiro", result: "VICTORIA", character: "Fola", mvp: "Demis", cover: "zafiro.jpg" }, { name: "Pokémon Z", result: "DERROTA", character: "Folana", mvp: "Ninguno", cover: "x.jpg" }], hallOfFame: [{ name: "Paaola", species: "Palossand", file: "palossand.gif" }, { name: "Lana", species: "Primarina", file: "primarina.gif" }, { name: "Cloyster", species: "Cloyster", file: "cloyster.gif" }] },
      2025: { series: [{ name: "Super Espada", result: "DERROTA", character: "Fola", mvp: "Desconocido", cover: "espada.jpg" }, { name: "Super Platino", result: "DERROTA", character: "Folana", mvp: "Ninguno", cover: "platino.jpg" }, { name: "Super Rubí", result: "DERROTA", character: "Fola", mvp: "Ninguno", cover: "rubi.jpg" }, { name: "Super Blanco 2", result: "VICTORIA", character: "Fola", mvp: "Equipo", cover: "black2.jpg" }, { name: "RubiusLocke", result: "DERROTA", character: "Fola", mvp: "Ninguno", cover: "firered.jpg" }], hallOfFame: [{ name: "Excadrill", species: "Excadrill", file: "excadrill.gif" }, { name: "Tyranitar", species: "Tyranitar", file: "tyranitar.gif" }, { name: "Volcarona", species: "Volcarona", file: "volcarona.gif" }] }
  },

  // --- OLIMPO OFICIAL (TOP 20) ---
  olympus: [
      { rank: 1, name: "Sisel", species: "Gliscor", file: "gliscor.gif", status: "Fallecido", kills: 84, series: "Rubí Omega Random", types: ["ground", "flying"], badge: "EL DIOS CAÍDO", lore: "La leyenda máxima. Murió trágicamente al nivel 100.", fullHistory: "Sisel no es solo un Pokémon, es una religión. Capturado como Gligar, fue entrenado manualmente hasta el nivel 100 por Fola, un esfuerzo titánico que creó un vínculo inquebrantable. En la Liga Pokémon, tras barrer equipos enteros con su Toxisfera y Terremoto, cayó ante un Rayo Hielo crítico de un Walrein de Fátima. Su muerte marcó el final espiritual de la serie más mítica del canal.", combatInfo: { ability: "Ímpetu Tóxico", item: "Toxisfera", moves: ["Terremoto", "Protección", "Tóxico", "Imagen"], stats: { hp: 75, atk: 95, def: 125, spa: 45, spd: 75, spe: 95 } } },
      { rank: 2, name: "Furia", species: "Typhlosion", file: "typhlosion.gif", status: "Vivo", kills: 62, series: "HeartGold Nuzlocke", types: ["fire"], badge: "EL PADRE", lore: "El inicio de todo. Venció a Rojo en el Monte Plateado.", fullHistory: "El padre de todos los lockes. Furia sobrevivió desde el laboratorio del Profesor Elm hasta la cima del Monte Plateado. Su batalla contra Rojo es historia de YouTube: estando a punto de morir, conectó un Estallido decisivo que le dio a Fola su primera gran victoria en un Nuzlocke completo. Es el símbolo de la perseverancia.", combatInfo: { ability: "Mar Llamas", item: "Gafas Elegid", moves: ["Estallido", "Lanzallamas", "Onda Certera", "Paranormal"], stats: { hp: 78, atk: 84, def: 78, spa: 109, spd: 85, spe: 100 } } },
      { rank: 3, name: "Paaola", species: "Palossand", file: "palossand.gif", status: "Vivo", kills: 25, series: "Super Sol Dual", types: ["ghost", "ground"], badge: "LA REINA", lore: "MVP Moderna. Tanqueó al Mega-Metagross de Frigo.", fullHistory: "En el locke más difícil y técnico, Paaola fue un muro inquebrantable. Su momento de gloria llegó en la final contra Frigo, donde tanqueó golpes imposibles del Mega-Metagross rival y respondió con un Tierra Viva que ganó el Dual. Demostró que la defensa gana campeonatos.", combatInfo: { ability: "Hidrorrefuerzo", item: "Restos", moves: ["Tierra Viva", "Bola Sombra", "Recogearena", "Defensa Férrea"], stats: { hp: 85, atk: 75, def: 110, spa: 100, spd: 75, spe: 35 } } },
      { rank: 4, name: "Ragnar", species: "Nidoking", file: "nidoking.gif", status: "Fallecido", kills: 45, series: "SoulSilver Dual", types: ["poison", "ground"], badge: "EL REY", lore: "Luz en la oscuridad. El único que cumplía mientras Fola perdía.", fullHistory: "Mientras Fola cometía error tras error en el Dual, Ragnar era la única esperanza. Con su cobertura de movimientos perfecta (Rayo Hielo, Tierra Viva, Lanzallamas), limpiaba equipos enteros él solo. Su muerte fue el momento en que la serie se sintió verdaderamente perdida. Un rey sin reino.", combatInfo: { ability: "Punto Tóxico", item: "Vidasfera", moves: ["Tierra Viva", "Onda Tóxica", "Rayo Hielo", "Lanzallamas"], stats: { hp: 81, atk: 102, def: 77, spa: 85, spd: 75, spe: 85 } } },
      { rank: 5, name: "Gunter", species: "Gengar", file: "gengar.gif", status: "Vivo", kills: 38, series: "Platino Random", types: ["ghost", "poison"], badge: "EL SALVADOR", lore: "Salvó la serie contra Cintia con un esquive milagroso.", fullHistory: "La batalla contra Cintia estaba perdida. Quedaba Gunter a un golpe de morir. El rival lanzó un ataque letal, pero Gunter lo esquivó milagrosamente y contraatacó con una Bola Sombra que ganó el Nuzlocke. Ese esquive es considerado intervención divina.", combatInfo: { ability: "Levitación", item: "Banda Focus", moves: ["Bola Sombra", "Bomba Lodo", "Rayo", "Mismo Destino"], stats: { hp: 60, atk: 65, def: 60, spa: 130, spd: 75, spe: 110 } } },
      { rank: 6, name: "Manolo", species: "Garchomp", file: "garchomp.gif", status: "Vivo", kills: 55, series: "Sol Random", types: ["dragon", "ground"], badge: "LA BESTIA", lore: "Fuerza bruta pura. 'Terremoto y a casa'.", fullHistory: "La definición de fuerza bruta. Manolo trivializó el locke de Alola con su velocidad y ataque monstruosos. Su estrategia era simple: Danza Espada y Terremoto. No requería pensar, solo destruir. Hizo que el juego pareciera fácil.", combatInfo: { ability: "Piel Tosca", item: "Casco Dentado", moves: ["Terremoto", "Garra Dragón", "Avalancha", "Danza Espada"], stats: { hp: 108, atk: 130, def: 95, spa: 80, spd: 85, spe: 102 } } },
      { rank: 7, name: "Knekro", species: "Mimikyu", file: "mimikyu.gif", status: "Vivo", kills: 20, series: "Luna Nuzlocke", types: ["ghost", "fairy"], badge: "EL ESCUDO", lore: "Su Disfraz fue la red de seguridad de toda la serie.", fullHistory: "El salvavidas de Fola. Gracias a su habilidad Disfraz, Knekro permitía a Fola curar o cambiar de estrategia sin recibir daño. Fue clave en los combates contra los Kahunas y en la Liga Pokémon, absorbiendo Movimientos Z que hubieran matado a cualquier otro.", combatInfo: { ability: "Disfraz", item: "Espectrostal Z", moves: ["Carantoña", "Garra Umbría", "Sombra Vil", "Danza Espada"], stats: { hp: 55, atk: 90, def: 80, spa: 50, spd: 105, spe: 96 } } },
      { rank: 8, name: "Turia", species: "Gyarados", file: "gyarados.gif", status: "Vivo", kills: 50, series: "Pokémon Iberia", types: ["water", "flying"], badge: "EL PATRIOTA", lore: "Héroe de España. Carrileó el fangame Iberia.", fullHistory: "En el fangame más difícil y memeable, Turia fue la seriedad y el poder. Con Danza Dragón, barrió gimnasios enteros basados en ciudades de España. Su consistencia fue clave para completar un juego lleno de trampas y niveles absurdos.", combatInfo: { ability: "Intimidación", item: "Restos", moves: ["Cascada", "Terremoto", "Danza Dragón", "Colmillo Hielo"], stats: { hp: 95, atk: 125, def: 79, spa: 60, spd: 100, spe: 81 } } },
      { rank: 9, name: "Laxus", species: "Luxray", file: "luxray.gif", status: "Vivo", kills: 32, series: "Platino Random", types: ["electric"], badge: "FAVORITO", lore: "Demostró que el amor gana a los stats.", fullHistory: "No era el más fuerte, ni el más rápido, pero era el favorito. Laxus protagonizó momentos donde sobrevivió a golpes críticos con 1 PS simplemente 'porque quería a su entrenador'. Fue el corazón del equipo en Sinnoh.", combatInfo: { ability: "Intimidación", item: "Imán", moves: ["Voltio Cruel", "Triturar", "Colmillo Hielo", "Onda Trueno"], stats: { hp: 80, atk: 120, def: 79, spa: 95, spd: 79, spe: 70 } } },
      { rank: 10, name: "Dolan", species: "Snorlax", file: "snorlax.gif", status: "Vivo", kills: 30, series: "Oro Calvolocke", types: ["normal"], badge: "LA MURALLA", lore: "Ganó el Calvolocke aburriendo a los rivales.", fullHistory: "En un reto donde perder un Pokémon significaba raparse la cabeza, Dolan fue el seguro de vida. Con Maldición y Descanso, se volvía inmortal y ganaba los combates por desgaste. Fue aburrido de ver, pero efectivo para salvar el pelo de Fola.", combatInfo: { ability: "Sebo", item: "Restos", moves: ["Maldición", "Descanso", "Golpe Cuerpo", "Triturar"], stats: { hp: 160, atk: 110, def: 65, spa: 65, spd: 110, spe: 30 } } },
      { rank: 11, name: "Hax", species: "Haxorus", file: "haxorus.gif", status: "Vivo", kills: 40, series: "UltraSol Dual", types: ["dragon"], badge: "DRAGON DANCE", lore: "Sweep legendario contra Frigo.", fullHistory: "El dragón definitivo. Su Danza Dragón en el momento justo le permitió barrer equipos enteros. Fue la espada que cortó la defensa de Frigo en el Dual.", combatInfo: { ability: "Rompedura", item: "", moves: [], stats: { hp: 76, atk: 147, def: 90, spa: 60, spd: 70, spe: 97 } } },
      { rank: 12, name: "Ursaluna", species: "Ursaluna", file: "ursaluna.gif", status: "Vivo", kills: 35, series: "Leyendas Arceus", types: ["ground", "normal"], badge: "MATADIOSES", lore: "Aguantó a Giratina y Volo.", fullHistory: "En el combate más difícil de la historia de Pokémon (Volo + Giratina), Ursaluna fue el tanque que aguantó los golpes de un dios. Su resistencia física fue clave para completar Leyendas Arceus.", combatInfo: { ability: "Agallas", item: "", moves: [], stats: { hp: 130, atk: 140, def: 105, spa: 45, spd: 80, spe: 50 } } },
      { rank: 13, name: "Luis", species: "Lucario", file: "lucario.gif", status: "Vivo", kills: 42, series: "Platino Mega", types: ["fighting", "steel"], badge: "EL AURA", lore: "Mega-Lucario Adaptable letal.", fullHistory: "Con su habilidad Adaptable al megaevolucionar, sus ataques de tipo Lucha y Acero pegaban el doble. Destrozó la Liga Pokémon de Sinnoh casi sin ayuda.", combatInfo: { ability: "Adaptable", item: "", moves: [], stats: { hp: 70, atk: 145, def: 88, spa: 140, spd: 70, spe: 112 } } },
      { rank: 14, name: "Greninja", species: "Greninja", file: "greninja.gif", status: "Vivo", kills: 40, series: "Platino Starters", types: ["water", "dark"], badge: "MUTATIPO", lore: "Rompió el Starterslocke.", fullHistory: "Su habilidad Mutatipo le daba STAB en todos los ataques y cambiaba sus debilidades defensivas. Fue un camaleón táctico que se adaptó a cada líder de gimnasio.", combatInfo: { ability: "Mutatipo", item: "", moves: [], stats: { hp: 72, atk: 95, def: 67, spa: 103, spd: 71, spe: 122 } } },
      { rank: 15, name: "Lavita", species: "Kingdra", file: "kingdra.gif", status: "Fallecido", kills: 28, series: "Rubí Omega", types: ["water", "dragon"], badge: "EL COMPAÑERO", lore: "Mano derecha de Sisel.", fullHistory: "Siempre a la sombra de Sisel, pero vital. Su tipo Agua/Dragón (solo débil a Dragón y Hada) lo hacía un cambio seguro en casi cualquier situación. Murió protegiendo al equipo.", combatInfo: { ability: "Francotirador", item: "", moves: [], stats: { hp: 75, atk: 95, def: 95, spa: 95, spd: 95, spe: 85 } } },
      { rank: 16, name: "Cloyster", species: "Cloyster", file: "cloyster.gif", status: "Vivo", kills: 18, series: "Super Rojo", types: ["water", "ice"], badge: "ROMPE BANDAS", lore: "Terror de Oscar Brock.", fullHistory: "Con la habilidad Encadenado y el ataque Carámbano, rompía las Bandas Focus y las habilidades de Robustez de los líderes de gimnasio. Fue la pesadilla de los rivales defensivos.", combatInfo: { ability: "Encadenado", item: "", moves: [], stats: { hp: 50, atk: 95, def: 180, spa: 85, spd: 45, spe: 70 } } },
      { rank: 17, name: "Don Quijote", species: "Gallade", file: "gallade.gif", status: "Vivo", kills: 22, series: "Iberia", types: ["psychic", "fighting"], badge: "CABALLERO", lore: "Escudero de Turia.", fullHistory: "El fiel compañero de Turia en Iberia. Cuando el Gyarados no podía salir por tipos eléctricos, Don Quijote entraba a limpiar con A Bocajarro y Psico-Corte.", combatInfo: { ability: "Justiciero", item: "", moves: [], stats: { hp: 68, atk: 125, def: 65, spa: 65, spd: 115, spe: 80 } } },
      { rank: 18, name: "Roberto", species: "Ampharos", file: "ampharos.gif", status: "Vivo", kills: 15, series: "HeartGold", types: ["electric"], badge: "EL FIEL", lore: "Siempre a la sombra de Furia.", fullHistory: "Lento pero resistente. Roberto paralizaba a los rivales y aguantaba golpes para que Furia pudiera entrar seguro. Un héroe silencioso del primer Nuzlocke.", combatInfo: { ability: "Elec. Estática", item: "", moves: [], stats: { hp: 90, atk: 75, def: 85, spa: 115, spd: 90, spe: 55 } } },
      { rank: 19, name: "Pee", species: "Swampert", file: "swampert.gif", status: "Vivo", kills: 12, series: "UltraSol Dual", types: ["water", "ground"], badge: "EL TANQUE", lore: "Aguantó para que Hax brillara.", fullHistory: "Su único trabajo era poner las rocas, aguantar golpes y cambiar de estado. Hizo el trabajo sucio para que Hax y Manolo se llevaran la gloria.", combatInfo: { ability: "Torrente", item: "", moves: [], stats: { hp: 100, atk: 110, def: 90, spa: 85, spd: 90, spe: 60 } } },
      { rank: 20, name: "Lana", species: "Primarina", file: "primarina.gif", status: "Vivo", kills: 10, series: "Super Sol Dual", types: ["water", "fairy"], badge: "SOPORTE", lore: "Compañera de Paaola.", fullHistory: "La compañera perfecta de Paaola. Cubría sus debilidades y curaba al equipo. Su Fuerza Lunar fue clave contra los dragones de la Liga.", combatInfo: { ability: "Torrente", item: "", moves: [], stats: { hp: 80, atk: 74, def: 74, spa: 126, spd: 116, spe: 60 } } }
  ],

  // --- COMUNIDAD & MENCIONES ---
  community: {
      top10: [
          { 
              rank: 1, name: "Crista", species: "Altaria", file: "altaria.gif", series: "Rubí Omega Random", 
              reason: "El Dios de Dioses.", 
              fullHistory: "La Mega Altaria que definió el Rubí Omega. Con su habilidad Piel Feérica, sus ataques de tipo Normal se convertían en Hada con una potencia devastadora. 'Vozarrón y a casa' era su lema. Fue, sin duda, el Pokémon más roto que ha pisado el canal." 
          },
          { 
              rank: 2, name: "Mr. Relax", species: "Medicham", file: "medicham.gif", series: "Oro Randomlocke", 
              reason: "Mataba legendarios de un golpe.", 
              fullHistory: "Gracias a su habilidad Energía Pura, Mr. Relax tenía el ataque físico más alto registrado en un Nuzlocke de Fola. Mataba legendarios como Mewtwo o Lugia de una sola Patada Salto Alta. Su muerte fue por un error de cálculo de Fola, no por falta de poder." 
          },
          { 
              rank: 3, name: "Jeito", species: "Klefki", file: "klefki.gif", series: "Pokémon Sun", 
              reason: "El MVP táctico.", 
              fullHistory: "Con su habilidad Bromista, Jeito ponía pantallas y cambios de estado con prioridad. Hizo que combates imposibles fueran manejables reduciendo el daño a la mitad para todo el equipo."
          },
          { 
              rank: 4, name: "Joel", species: "Incineroar", file: "incineroar.gif", series: "Luna Nuzlocke", 
              reason: "El único superviviente.", 
              fullHistory: "En un Nuzlocke donde todos murieron, Joel fue el 'Último Hombre en Pie'. Aguantó crítico tras crítico y ganó la liga siendo el único Pokémon vivo del equipo. Un verdadero superviviente."
          },
          { 
              rank: 5, name: "Villegas", species: "Tentacruel", file: "tentacruel.gif", series: "Plata Hardlocke", 
              reason: "Ancla defensiva.", 
              fullHistory: "Nadie daba un duro por un Tentacool, pero Villegas evolucionó en una muralla especial impenetrable. Aguantó 50 episodios recibiendo los ataques más fuertes de los líderes de gimnasio."
          },
          { 
              rank: 6, name: "Gordillo", species: "Pachirisu", file: "pachirisu.gif", series: "Plata Dual Locke", 
              reason: "Bendecido por Dios.", 
              fullHistory: "Un Pachirisu que sobrevivió a Terremotos y ataques de legendarios. La comunidad estaba convencida de que el juego estaba bugueado o que Dios intervenía cada vez que Gordillo salía al campo."
          },
          { 
              rank: 7, name: "Demis", species: "Chansey", file: "chansey.gif", series: "Super Zafiro", 
              reason: "Muralla definitiva.", 
              fullHistory: "Con el objeto Mineral Evol, Demis tenía más defensa especial que Arceus. Podía stallear (desgastar) a cualquier rival especial del juego simplemente curándose y usando Tóxico."
          },
          { 
              rank: 8, name: "Gio", species: "Delphox", file: "delphox.gif", series: "X Randomlocke", 
              reason: "Potencia legendaria.", 
              fullHistory: "El starter que nadie quería pero que terminó cerrando bocas. En el X Randomlocke, Gio demostró que la magia de fuego es superior. Su Llama Embrujada y Psíquico fueron claves para superar la Liga."
          },
          { 
              rank: 9, name: "Joel", species: "Empoleon", file: "empoleon.gif", series: "Platino Starters", 
              reason: "Primer starter ganador.", 
              fullHistory: "Rompió la maldición del starter (donde Fola siempre perdía a su inicial). Joel aguantó todo el juego y demostró que el tipo Acero es el mejor defensivo."
          },
          { 
              rank: 10, name: "Scrafy", species: "Scrafty", file: "scrafty.gif", series: "Negro 2 Dual", 
              reason: "Mató al 50% de Iris.", 
              fullHistory: "En la final contra la Campeona Iris, Scrafy se cargó a la mitad de su equipo de dragones usando Puño Hielo y Drenadoras. Fue el MVP silencioso de esa final."
          }
      ],
      
      // --- MENCIONES HONORÍFICAS (DATOS COMPLETOS) ---
      mentions: [
          { name: "Lleras", species: "Clawitzer", file: "clawitzer.gif", series: "X Random", role: "Francotirador", fullHistory: "Un cañón de cristal. Su habilidad Megadisparador hacía que sus ataques de aura pegaran como camiones. Fue clave en el mid-game de Pokémon X." },
          { name: "Banos", species: "Tyranitar", file: "tyranitar.gif", series: "Rubí Omega", role: "Tanque", fullHistory: "El tanque de arena. Invocaba la tormenta de arena que desgastaba a los rivales mientras él aguantaba todo." },
          { name: "Cero", species: "Porygon-Z", file: "porygon-z.gif", series: "Platino", role: "Glass Cannon", fullHistory: "Con su Adaptable y Triataque, borraba enemigos del mapa. Frágil pero letal." },
          { name: "Dorta", species: "Venusaur", file: "venusaur.gif", series: "Rojo Fuego", role: "Veterano", fullHistory: "El veterano que aguantó todo Kanto. Drenadoras y Polvo Sueño fueron su firma." },
          { name: "Gemita", species: "Garchomp", file: "garchomp.gif", series: "Diamante", role: "Reina", fullHistory: "La reina de Sinnoh. Hizo pareja con Fola en el Dual y demostró por qué Garchomp está roto." },
          { name: "Evans", species: "Charizard", file: "charizard.gif", series: "X Random", role: "Fuego", fullHistory: "El dragón que no era dragón. Sus Vuelo y Lanzallamas salvaron a Fola de muchos apuros." },
          { name: "Filero", species: "Heracross", file: "heracross.gif", series: "HeartGold", role: "Luchador", fullHistory: "Con A Bocajarro y Megacuerno, no había muro que lo parara. Un luchador nato." },
          { name: "Barak", species: "Vikavolt", file: "vikavolt.gif", series: "Sol/Luna", role: "Voltaje", fullHistory: "Lento pero seguro. Su Rayo era sentencia de muerte para cualquier volador o agua." },
          { name: "Sim", species: "Rotom", file: "rotom.gif", series: "Platino", role: "Electro", fullHistory: "La lavadora de la muerte. Su combinación de tipos y levitación lo hacían intocable." },
          { name: "Flop", species: "Lopunny", file: "lopunny.gif", series: "Diamante", role: "Speed", fullHistory: "Demostró que con Retribución y velocidad se puede ganar. Nadie daba nada por él." },
          { name: "Galus", species: "Gallade", file: "gallade.gif", series: "Rubí Omega", role: "Espadachín", fullHistory: "El caballero. Su Psico-Corte crítico era legendario." },
          { name: "Empanadita", species: "Golem", file: "golem.gif", series: "SoulSilver", role: "Roca", fullHistory: "Explosión... a veces. Pero mayormente un tanque físico impenetrable." },
          { name: "Maní", species: "Snorlax", file: "snorlax.gif", series: "X e Y", role: "Muro", fullHistory: "Giga Impacto y a dormir. La estrategia más simple y efectiva." },
          { name: "Felicia", species: "Gardevoir", file: "gardevoir.gif", series: "Zafiro Alfa", role: "Psíquico", fullHistory: "La protectora del equipo con sus pantallas y Fuerza Lunar." },
          { name: "Dark", species: "Zoroark", file: "zoroark.gif", series: "Blanco/Negro", role: "Ilusionista", fullHistory: "El maestro del engaño. Ganó combates confundiendo a la IA con su ilusión." },
          { name: "Goku", species: "Infernape", file: "infernape.gif", series: "Platino", role: "Luchador", fullHistory: "Rápido, fuerte y versátil. El starter de fuego definitivo de Sinnoh." },
          { name: "Draga", species: "Dragonite", file: "dragonite.gif", series: "HeartGold", role: "Multiscale", fullHistory: "Multiscale lo hacía aguantar un golpe seguro y devolverlo con un Enfado nuclear." }
      ]
  }
};